modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/CodeOfArdonia/TooltipsReforged/issues"
license = "MIT"

[[mods]]
modId = "tooltips_reforged"
version = "${version}"
displayName = "Tooltips Reforged"
authors = "IAFEnvoy"
description = '''
Fully remake the whole tooltips and add various functions
'''
logoFile = "logo.png"

[[dependencies.tooltips_reforged]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tooltips_reforged]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.5)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tooltips_reforged]]
modId = "jupiter"
mandatory = true
versionRange = "[2,)"
ordering = "NONE"
side = "BOTH"
